version: "3.9"

services:
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=mysqlpw
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./base/my.cnf:/etc/mysql/conf.d/my.cnf # Archivo de configuración personalizado


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - mysql
    ports:
      - "5001:5000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    depends_on:
      - backend

volumes:
  mysql_data:
